# Generated by Django 4.1.1 on 2022-09-07 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
                ('number_of_days', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('maximum', models.DecimalField(decimal_places=2, max_digits=4)),
                ('minimum', models.DecimalField(decimal_places=2, max_digits=4)),
                ('average', models.DecimalField(decimal_places=2, max_digits=4)),
                ('median', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
